# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.TextField()),
                ('naam_kort', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vliegveld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.TextField()),
                ('afkorting_icao', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Vliegveld'),
        ),
    ]
