# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vliegveld',
            name='naam',
            field=models.CharField(max_length=30),
        ),
    ]
