# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0002_auto_20161215_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opleiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Startwijze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
            ],
        ),
    ]
