# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0003_opleiding_startwijze'),
    ]

    operations = [
        migrations.AddField(
            model_name='startwijze',
            name='naam_kort',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
