# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0004_startwijze_naam_kort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_voorval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voorval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingave', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField()),
                ('uur', models.TimeField()),
                ('synopsis', models.TextField()),
                ('opleiding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Opleiding')),
                ('startwijze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Startwijze')),
                ('type_voorval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Type_voorval')),
            ],
        ),
    ]
