# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0005_type_voorval_voorval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_toestel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
            ],
        ),
    ]
