# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_ia', '0006_type_toestel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='opleiding',
            options={'verbose_name_plural': 'Opleidingen'},
        ),
        migrations.AlterModelOptions(
            name='startwijze',
            options={'verbose_name_plural': 'Startwijzen'},
        ),
        migrations.AlterModelOptions(
            name='type_toestel',
            options={'verbose_name_plural': 'Type toestellen'},
        ),
        migrations.AlterModelOptions(
            name='type_voorval',
            options={'verbose_name_plural': 'Type voorvallen'},
        ),
        migrations.AlterModelOptions(
            name='vliegveld',
            options={'verbose_name_plural': 'Vliegvelden'},
        ),
        migrations.AlterModelOptions(
            name='voorval',
            options={'verbose_name_plural': 'Voorvallen'},
        ),
    ]
