# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0007_auto_20161227_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='voorval',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Club'),
        ),
    ]
