# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0008_voorval_club'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Ato_gebruiker',
        ),
    ]
