# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0009_auto_20161229_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorval',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Club'),
        ),
    ]
