# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0010_auto_20161229_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kern_activiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kern activiteit',
            },
        ),
        migrations.CreateModel(
            name='Schade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menselijk', models.BooleanField(default=False)),
                ('materieel', models.BooleanField(default=False)),
                ('omschrijving', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Schade',
            },
        ),
        migrations.AddField(
            model_name='voorval',
            name='muopo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mens'), (2, 'Uitrusting'), (3, 'Omgeving'), (4, 'Product'), (5, 'Organisatie')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
