# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0012_auto_20170104_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voorval',
            old_name='materieel',
            new_name='materiele_schade',
        ),
        migrations.RenameField(
            model_name='voorval',
            old_name='menselijk',
            new_name='menselijke_schade',
        ),
    ]
