# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0013_auto_20170104_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kern_gevaar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kern gevaar',
            },
        ),
        migrations.CreateModel(
            name='Potentieel_risico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Potentieel_risico',
            },
        ),
    ]
