# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0017_auto_20170112_0836'),
    ]

    operations = [
                 migrations.RunSQL(["""
CREATE OR REPLACE FUNCTION update_voorval_aantal_maatregelen()
RETURNS "trigger" AS
$BODY$
DECLARE
        a_maatregelen INTEGER;	
BEGIN
        SELECT INTO a_maatregelen aantal_maatregelen FROM report_ia_voorval
		WHERE id = NEW.voorval_id;
        IF TG_OP = 'INSERT' THEN
           UPDATE report_ia_voorval SET aantal_maatregelen = a_maatregelen + 1
           	WHERE id = NEW.voorval_id;
	ELSEIF TG_OP = 'DELETE' THEN
	   UPDATE report_ia_voorval SET aantal_maatregelen = a_maatregelen - 1
           	WHERE id = NEW.voorval_id;
	END IF;
        RETURN NEW;
END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE;
ALTER FUNCTION update_voorval_aantal_maatregelen() OWNER TO ato_admin;
"""])
    ]
