# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0018_auto_20170113_1121'),
    ]

    operations = [
        migrations.RunSQL(["""
        CREATE TRIGGER check_aantallen
    AFTER INSERT OR DELETE ON report_ia_maatregel
    FOR EACH ROW
    EXECUTE PROCEDURE update_voorval_aantal_maatregelen();
    """])
        ]
