# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0019_auto_20170113_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='voorval',
            name='aantal_maatregelen',
            field=models.IntegerField(default=0),
        ),
    ]
