# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0023_auto_20170116_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='voorval',
            name='ato',
            field=models.IntegerField(choices=[(1, 'ATO voorval'), (2, 'niet ATO voorval')], default=1),
        ),
    ]
