# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0025_voorval_potentieel_risico'),
    ]

    operations = [
        migrations.AddField(
            model_name='maatregel',
            name='invoege',
            field=models.DateField(null=True),
        ),
    ]
