# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0026_maatregel_invoege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maatregel',
            options={'ordering': ['-ingave'], 'verbose_name_plural': 'Maatregelen'},
        ),
        migrations.AlterModelOptions(
            name='voorval',
            options={'ordering': ['-datum'], 'verbose_name_plural': 'Voorvallen'},
        ),
        migrations.RenameField(
            model_name='maatregel',
            old_name='invoege',
            new_name='in_werking',
        ),
        migrations.AlterField(
            model_name='voorval',
            name='datum',
            field=models.DateField(help_text='Datum van het voorval'),
        ),
    ]
