# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 19:16
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0027_auto_20170117_1456'),
    ]

    operations = [
        migrations.RunSQL(["""
        drop view voorval_maatregel;
        """]),                           
        migrations.AlterField(
            model_name='voorval',
            name='muopo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mens'), (2, 'Uitrusting'), (3, 'Omgeving'), (4, 'Product'), (5, 'Organisatie')], max_length=5),
        ),
        migrations.RunSQL(["""
 CREATE OR REPLACE VIEW voorval_maatregel AS 
 SELECT row_number() OVER () AS id,
    vv.datum as datum_voorval,
    vv.uur,
    vv.ato,
    vv.type_voorval_id,
    vv.synopsis,
    vv.opleiding_id,
    vv.startwijze_id,
    vv.club_id,
    vv.menselijke_schade,
    vv.materiele_schade,
    vv.muopo,
    vv.type_toestel_id,
    vv.kern_activiteit_id,
    vv.schade_omschrijving,
    ma.omschrijving as maatregel_omschrijving,
    ma.in_werking
   FROM report_ia_voorval vv
     LEFT JOIN report_ia_maatregel ma ON ma.voorval_id = vv.id;

ALTER TABLE voorval_maatregel
  OWNER TO ato_admin;
"""]),        
    ]
