# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0032_auto_20170118_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='nieuws',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
