# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0034_auto_20170119_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='AantalStarts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_datum', models.DateField(auto_now=True)),
                ('lier', models.IntegerField(blank=True, default=0)),
                ('ato_lier', models.IntegerField(blank=True, default=0)),
                ('sleep', models.IntegerField(blank=True, default=0)),
                ('ato_sleep', models.IntegerField(blank=True, default=0)),
                ('zelf', models.IntegerField(blank=True, default=0)),
                ('ato_zelf', models.IntegerField(blank=True, default=0)),
                ('totaal', models.IntegerField(blank=True, default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Club')),
            ],
            options={
                'verbose_name_plural': 'Aantal starts',
            },
        ),
    ]
