# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0035_aantalstarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aantalstarts',
            name='lier',
            field=models.IntegerField(default=0),
        ),
    ]
