# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0036_auto_20170120_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.DateTimeField(auto_now=True)),
                ('bestand', models.FileField(upload_to='')),
                ('opmerking', models.TextField()),
                ('voorval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Voorval')),
            ],
            options={
                'verbose_name_plural': 'Bestanden',
            },
        ),
        migrations.AlterField(
            model_name='aantalstarts',
            name='lier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
