# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import report_ia.models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0037_auto_20170130_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='voorval',
            name='aantal_bestanden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='bestand',
            field=models.FileField(upload_to=report_ia.models.club_directory_path),
        ),
    ]
