# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0038_auto_20170201_1003'),
    ]

    operations = [
                                 migrations.RunSQL(["""
CREATE OR REPLACE FUNCTION update_voorval_aantal_bestanden()
RETURNS "trigger" AS
$BODY$
DECLARE
        a_bestanden INTEGER;	
BEGIN
        IF TG_OP = 'INSERT' THEN
          SELECT INTO a_bestanden aantal_bestanden FROM report_ia_voorval
	 	WHERE id = NEW.voorval_id;
           UPDATE report_ia_voorval SET aantal_bestanden = a_bestanden + 1
           	WHERE id = NEW.voorval_id;
	ELSEIF TG_OP = 'DELETE' THEN
           SELECT INTO a_bestanden aantal_bestanden FROM report_ia_voorval
		WHERE id = OLD.voorval_id;
	   UPDATE report_ia_voorval SET aantal_bestanden = a_bestanden - 1
           	WHERE id = OLD.voorval_id;
	END IF;
        RETURN NEW;
END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE;
ALTER FUNCTION update_voorval_aantal_bestanden() OWNER TO ato_admin;
"""]),
                migrations.RunSQL(["""
        CREATE TRIGGER check_aantallen2
    AFTER INSERT OR DELETE ON report_ia_bestand
    FOR EACH ROW
    EXECUTE PROCEDURE update_voorval_aantal_bestanden();
    """])

    ]
