# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0040_auto_20170208_2150'),
    ]

    operations = [
        migrations.RunSQL(["""
TRUNCATE report_ia_voorval CASCADE;
TRUNCATE report_ia_type_toestel CASCADE;
ALTER SEQUENCE report_ia_type_toestel_id_seq RESTART WITH 1;
ALTER SEQUENCE report_ia_voorval_id_seq RESTART WITH 1;
ALTER SEQUENCE report_ia_maatregelen_id_seq RESTART WITH 1;
ALTER SEQUENCE report_ia_bestand_id_seq RESTART WITH 1;
COPY report_ia_type_toestel (naam ) FROM '/home/jpe/proj/ato/ato/db/zwevers.csv' WITH (FORMAT CSV, ENCODING UTF8);
"""]),
    ]
