# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0044_auto_20170213_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_schade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Type schades',
            },
        ),
        migrations.RemoveField(
            model_name='voorval',
            name='materiele_schade',
        ),
        migrations.RemoveField(
            model_name='voorval',
            name='menselijke_schade',
        ),
        migrations.AddField(
            model_name='voorval',
            name='type_schade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Type_schade'),
            preserve_default=False,
        ),
    ]
