# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0048_auto_20170306_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='aantalstarts',
            name='ato_auto',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='aantalstarts',
            name='ato_bungee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='aantalstarts',
            name='auto',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='aantalstarts',
            name='bungee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='andere_locatie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='locatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Vliegveld'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='schade_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
