# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0049_auto_20170310_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='aantalstarts',
            name='ato_vliegdagen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='aantalstarts',
            name='vliegdagen',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
