# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0051_auto_20170328_0902'),
    ]

    operations = [
                migrations.RunSQL(["""
 DROP VIEW voorval_maatregel;                
 CREATE OR REPLACE VIEW voorval_maatregel AS 
 SELECT row_number() OVER () AS id,
    vv.datum AS datum_voorval,
    vv.uur,
    vv.ato,
    vv.type_voorval_id,
    vv.synopsis,
    vv.opleiding_id,
    vv.startwijze_id,
    vv.club_id,
    vv.type_schade_id,
    vv.schade_omschrijving,
    vv.mens,
    vv.uitrusting,
    vv.omgeving,
    vv.product,
    vv.organisatie,
    vv.type_toestel_id,
    vv.kern_activiteit_id,
    vv.windsterkte_id,
    vv.windrichting_id,
    vv.wolken_id,
    vv.wolkenbasis_id,
    vv.thermiek_id,
    vv.zichtbaarheid_id,
    ma.omschrijving AS maatregel_omschrijving,
    ma.in_werking
   FROM report_ia_voorval vv
     LEFT JOIN report_ia_maatregel ma ON ma.voorval_id = vv.id;

ALTER TABLE voorval_maatregel
  OWNER TO ato_admin;
"""])

    ]
