# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0052_auto_20170328_1506'),
    ]

    operations = [
                migrations.RunSQL(["""
TRUNCATE report_ia_voorval CASCADE;
TRUNCATE report_ia_kern_activiteit CASCADE;
ALTER SEQUENCE report_ia_kern_activiteit_id_seq RESTART WITH 1;
ALTER SEQUENCE report_ia_voorval_id_seq RESTART WITH 1;
ALTER SEQUENCE report_ia_maatregelen_id_seq RESTART WITH 1;
ALTER SEQUENCE report_ia_bestand_id_seq RESTART WITH 1;
COPY report_ia_kern_activiteit (naam ) FROM '/home/jpe/proj/ato/ato/db/kernactiviteiten.csv' WITH (FORMAT CSV, ENCODING UTF8, DELIMITER '|');
"""]),
    ]
