# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0054_auto_20170405_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aantalstarts',
            old_name='totaal',
            new_name='totaal_starts',
        ),
        migrations.AddField(
            model_name='aantalstarts',
            name='totaal_vliegdagen',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
