# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0055_auto_20170405_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aantalstarts',
            name='ingevuld_op',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
