# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0056_auto_20170405_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aantalstarts',
            name='ingevuld_op',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='thermiek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Thermiek'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='windrichting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Windrichting'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='windsterkte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Windsterkte'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='wolken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Wolken'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='wolkenbasis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Wolkenbasis'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='zichtbaarheid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Zichtbaarheid'),
        ),
    ]
