# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0058_auto_20170406_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aantalstarts',
            name='totaal_vliegdagen',
        ),
    ]
