# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0059_remove_aantalstarts_totaal_vliegdagen'),
    ]

    operations = [
    ]
