# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0062_auto_20170406_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='voorval',
            name='muopo_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
