# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0064_remove_voorval_potentieel_risico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aantalstarts',
            name='ato_vliegdagen',
        ),
    ]
