# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0065_remove_aantalstarts_ato_vliegdagen'),
    ]

    operations = [
        migrations.RunSQL(["""
TRUNCATE report_ia_voorval CASCADE;
ALTER SEQUENCE report_ia_voorval_id_seq RESTART WITH 1;
"""]),        
        migrations.CreateModel(
            name='Domein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='voorval',
            name='ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_ia.Domein'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='opleiding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Opleiding'),
        ),
                migrations.RunSQL(["""
insert into report_ia_domein (naam) values ('ATO voorval');
insert into report_ia_domein (naam) values ('niet ATO voorval');
insert into report_ia_domein (naam) values ('onduidelijk (ATO/niet ATO voorval');
"""]),

    ]
