# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0068_auto_20170411_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voorval',
            old_name='ato',
            new_name='domein',
        ),
                               migrations.RunSQL(["""
TRUNCATE report_ia_voorval CASCADE;                       
 DROP VIEW voorval_maatregel;
 CREATE OR REPLACE VIEW voorval_maatregel AS
 SELECT row_number() OVER () AS id,
    vv.datum AS datum_voorval,
    vv.uur,
    vv.domein_id,
    vv.type_voorval_id,
    vv.synopsis,
    vv.opleiding_id,
    vv.startwijze_id,
    vv.club_id,
    vv.type_schade_id,
    vv.schade_omschrijving,
    vv.mens,
    vv.uitrusting,
    vv.omgeving,
    vv.product,
    vv.organisatie,
    vv.muopo_omschrijving,
    vv.type_toestel_id,
    vv.kern_activiteit_id,
    vv.windsterkte_id,
    vv.windrichting_id,
    vv.wolken_id,
    vv.wolkenbasis_id,
    vv.thermiek_id,
    vv.zichtbaarheid_id,
    ma.omschrijving AS maatregel_omschrijving,
    ma.in_werking
   FROM report_ia_voorval vv
     LEFT JOIN report_ia_maatregel ma ON ma.voorval_id = vv.id;

ALTER TABLE voorval_maatregel
  OWNER TO ato_admin;
"""])
  
    ]
