# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0071_auto_20170426_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kern_activiteit',
            options={'ordering': ['prio'], 'verbose_name_plural': 'Kern activiteit'},
        ),
        migrations.AlterField(
            model_name='windrichting',
            name='uit',
            field=models.CharField(max_length=10),
        ),
    ]
