# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0072_auto_20171013_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_mail',
            name='ato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club_mail',
            name='non_ato',
            field=models.BooleanField(default=False),
        ),
    ]
