# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0074_club_mail_funktie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_mail',
            name='funktie',
            field=models.CharField(default='', max_length=100),
        ),
    ]
