# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_ia', '0075_auto_20171023_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voorval',
            name='startwijze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Startwijze'),
        ),
        migrations.AlterField(
            model_name='voorval',
            name='type_toestel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_ia.Type_toestel'),
        ),
    ]
